### PR TITLE
no idea what to write for a title (yea me neither -MEEP)

### PR DESCRIPTION
**Pull request by QmelZ**

### CODE REVIEW

**Comment by MEEPofFaith** [comment]
I still don't know the benefit for using `Events.on` over `Events.run` are, I haven't encountered any issues.

**Comment by QmelZ** [comment]
basically, events.on runs on event and events.run runs

**Comment by MEEPofFaith** [comment]
I have no idea what that means.

**Comment by QmelZ** [comment]
well, i dont either, so...

**Pull request closed without merging**
